---
db:
  host: "92.63.64.241"
  port: "52136"
  user: "naimix"
  password: "naimix"
  name: "naimix"

server:
  host: "0.0.0.0"
  port: "80"

auth:
  salt: "ahbbraegr345a"
  signingKey: "tqtqbsabsdf4"
  timeToLive: 1024m

adminMigration:
  adminID: "94a123a8-711d-11ee-a2d8-0251c0a8f004"
  adminUserName: "admin"
  adminEmail: "admin@example.com"
  adminPassword: "admin"

smtpConfig:
  host: "smtp.gmail.com"
  port: "587"
  user: "www.carat.ru@gmail.com"
  password: "fjto ywhd mhot ejee"

mail:
  mail: "www.carat@list.ru"

minio:
  endpoint: "minio.freydin.space"
  accessKey: "5AXO7Y9mZj0QywAN"
  secretKey: "fLlNJ18GmXT8bIe3AXxZVeMGNllGR99Y"
  token: ""
  useSSL: true

cameoMetricsHttpClient:
  url: https://metrics.naimix.cameo.freydin.space


